name: Publish Documentation

on:
  workflow_run:
    workflows: ["Build Project"]
    branches: [master]
    types: [completed]
  schedule:
    - cron: '30 0 * * *'  # Run 30 minutes after the build workflow

env:
  JAVA_VERSION: '17'
  MAVEN_VERSION: '3.9.5'
  MAVEN_OPTS: '-Xmx3072m'

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

jobs:
  publish:
    name: Generate and publish documentation
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'schedule' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        if: ${{ github.event_name != 'schedule' }}
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-ubuntu-latest
          path: target/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        if: ${{ github.event_name == 'schedule' }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Download artifacts fallback
        if: ${{ github.event_name == 'schedule' }}
        run: |
          ./.run.builds.sh

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.1'

      - name: Install Jekyll dependencies
        run: ./.run.jekyll.sh

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site/
          retention-days: 1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          timeout: 600000  # 10-minute timeout
