name: Publish the how-to

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run builds
        run: |
          mkdir --parents "$HOME/.local/bin"
          ls -lrta "$HOME/.local/bin"
          curl -sL https://github.com/protocolbuffers/protobuf-javascript/releases/download/v3.21.4/protobuf-javascript-3.21.4-linux-x86_64.tar.gz | tar xzfO - bin/protoc-gen-js > "$HOME/.local/bin/protoc-gen-js"
          chmod u+x "$HOME/.local/bin/protoc-gen-js"
          curl -sL https://github.com/grpc/grpc-web/releases/download/1.5.0/protoc-gen-grpc-web-1.5.0-linux-x86_64 > "$HOME/.local/bin/protoc-gen-grpc-web"
          chmod u+x "$HOME/.local/bin/protoc-gen-grpc-web"
          ./.run.builds.sh
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.1'
      - name: Run Jekyll and deploy
        run: ./.run.jekyll.sh
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
